FROM ghcr.io/dockhippie/ubuntu:22.04-arm@sha256:2d39d8c34f8c2cb01ddf670f9078b08f5b6d0ddb048775689b5d9bb9444b695d

WORKDIR /srv/app

RUN apt-get update && \
  apt-get install -y lsb-release gnupg2 && \
  curl -sSL https://packages.adoptium.net/artifactory/api/gpg/key/public | apt-key add - && \
  echo "deb https://packages.adoptium.net/artifactory/deb $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/temurin.list && \
  apt-get update && \
  apt-get upgrade -y && \
  apt-get install -y temurin-17-jdk libatomic1 ca-certificates ca-certificates-java && \
  ln -sf /etc/ssl/certs/java/cacerts /etc/ssl/certs/adoptium/cacerts && \
  apt-get purge -y lsb-release gnupg2 && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*

COPY ./overlay /
