FROM ghcr.io/dockhippie/ubuntu:22.04-arm64@sha256:b39dc85a55c2140e8ce8833f81386ae09488f001e7be9e478aeb8449833515f5

WORKDIR /srv/app

RUN apt-get update && \
  apt-get install -y lsb-release gnupg2 && \
  curl -sSL https://packages.adoptium.net/artifactory/api/gpg/key/public | apt-key add - && \
  echo "deb https://packages.adoptium.net/artifactory/deb $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/temurin.list && \
  apt-get update && \
  apt-get upgrade -y && \
  apt-get install -y temurin-20-jdk libatomic1 ca-certificates ca-certificates-java && \
  ln -sf /etc/ssl/certs/java/cacerts /etc/ssl/certs/adoptium/cacerts && \
  apt-get purge -y lsb-release gnupg2 && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*

COPY ./overlay /
