FROM webhippie/ubuntu:20.04-arm64@sha256:7df352a64d615148a5387fbf180dc4500de3f8d49f59218b4cd58ec87c448b0b

WORKDIR /srv/app

RUN apt-get update && \
  apt-get install -y lsb-release gnupg2 && \
  curl -sSL https://packages.adoptium.net/artifactory/api/gpg/key/public | apt-key add - && \
  echo "deb https://packages.adoptium.net/artifactory/deb $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/temurin.list && \
  apt-get update && \
  apt-get upgrade -y && \
  apt-get install -y temurin-18-jdk libatomic1 ca-certificates ca-certificates-java && \
  ln -sf /etc/ssl/certs/java/cacerts /etc/ssl/certs/adoptium/cacerts && \
  apt-get purge -y lsb-release gnupg2 && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*

COPY ./overlay /
