FROM webhippie/ubuntu:20.04-arm64@sha256:ca7b96e1e1d75bd05578117a231046e6f34acef9f054f46a55ce8d71a2398c02

WORKDIR /srv/app

RUN apt-get update && \
  apt-get install -y lsb-release gnupg2 && \
  curl -sSL https://packages.adoptium.net/artifactory/api/gpg/key/public | apt-key add - && \
  echo "deb https://packages.adoptium.net/artifactory/deb $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/temurin.list && \
  apt-get update && \
  apt-get upgrade -y && \
  apt-get install -y temurin-8-jdk libatomic1 ca-certificates ca-certificates-java && \
  ln -sf /etc/ssl/certs/java/cacerts /etc/ssl/certs/adoptium/cacerts && \
  apt-get purge -y lsb-release gnupg2 && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*

COPY ./overlay /
